### ISSUE TITLE
[JOSS]: Pytest execution instructions 

### ISSUE THREAD

**Issue by trevorb1** [UU-ER/AdOpT-NET0#328]
To run tests, the docs say to run the following command: 

```bash
coverage run -m pytest
```

However, I received the following error and had to `pip install coverage`. 

```bash
$ coverage run -m pytest
coverage: command not found
```

Please either create a desperate developer install version of your package (with optional dependencies) or update instructions to include the `coverage` requirement (if this issue can be replicated by your development team).

**Comment by JeanWi** [comment]
We have changed the building and dependency management to poetry in #320, now also including test and development dependency groups - does this make sense to you?

**Comment by trevorb1** [comment]
Makes sense to me! Thanks @JeanWi!
