### ISSUE TITLE
Documentation should default to last stable version and not "latest"

### ISSUE THREAD

**Issue by AdamRJensen** [UU-ER/AdOpT-NET0#384]
Currently, the documentation site https://adopt-net0.readthedocs.io redirects to the latest version (https://adopt-net0.readthedocs.io/en/latest/).

This is not desired as this version is not what a user would get by using pip install. The latest version is what a user would get if installing from the github repo and is thus unversioned (not desireable).

**Comment by AdamRJensen** [comment]
@JeanWi Could you also update the link on GitHub (simply remove "en/latests":

![image](https://github.com/user-attachments/assets/b76d4d5a-e399-40c5-9135-01d089589fd2)

**Comment by JeanWi** [comment]
Absolutely! Thanks :)
