### ISSUE TITLE
What is a CO2 network?

### ISSUE THREAD

**Issue by AdamRJensen** [UU-ER/AdOpT-NET0#387]
Hydrogen and electricity networks make sense to me, but what is CO2 networks?

https://github.com/UU-ER/AdOpT-NET0/blob/d9a863069f0c120d1f849f0756081a2d725ee9ff/joss_submission/paper.md?plain=1#L42

**Comment by lucabert01** [comment]
Dear Adam, 

Thank you for your question. With CO2 networks, we refer to the infrastructure needed to transport captured CO2 from, e.g., industrial facilities with CCS, connecting the sources with the sinks (typically depleted gas fields or saline aquifers). In AdOpT, we have only pipelines so far, but trucks, ships, and trains will be added as part of my PhD project. Some examples of relevant literature on CO2 networks are https://doi.org/10.1016/j.ijggc.2021.103372 and https://doi.org/10.1016/j.ijggc.2022.103635.

Please let us know if you would like us to add further information about that in the paper

**Comment by AdamRJensen** [comment]
I accept it. Thanks for the info!
